.TH "PKGBYUSER" "1" "July 2009" "" ""
.SH "NAME"
pkgbyuser \- a simple script to download all packages by a user

.SH "SYNOPSIS"
pkgbyuser [username]
.SH "DESCRIPTION"
Pkgbyuser is a simple script that allows you to download all (or some) packages from [unsupported] that are maintained by a given user.
.SH "OPTIONS"
.TP 
\fB\-e\fR, \fB\-\-extract\fR
Extract some (or all) of the downloaded packages
.TP 
\fB\-ec\fR, \fB\-\-clean\fR
Same as \-e but removes extracted archives
.SH "AUTHORS"
Ghost1227
